apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexaconverseai-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nexaconverseai
  template:
    metadata:
      labels:
        app: nexaconverseai
    spec:
      containers:
      - name: nexaconverseai
        image: yourdockerhubusername/nexaconverseai:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"